GET http://localhost:8880/ebook/list?page=1&size=4&name=java
###
GET http://localhost:8880/ebook/all?page=1&size=4&category2=2001

###

POST http://localhost:80/api/item
Content-Type: application/json

{}

###